export default function PolicyPage() {
  return (
    <main>
      <h1 style={{ fontSize: 24, marginBottom: 8 }}>StudyAgent research policy</h1>
      <p style={{ marginTop: 0, marginBottom: 12, color: '#4b5563', maxWidth: 640 }}>
        StudyAgent is a research prototype to explore better ways of helping students learn from their notes and
        problem sets.
      </p>
      <ul style={{ paddingLeft: 18, fontSize: 14, color: '#374151', maxWidth: 720 }}>
        <li style={{ marginBottom: 6 }}>
          Your uploads and tutor conversations may be logged and used to understand how the system is used and to
          improve models and prompts.
        </li>
        <li style={{ marginBottom: 6 }}>
          Logs may include text from your notes, questions, and answers generated by the system.
        </li>
        <li style={{ marginBottom: 6 }}>
          Data is only used in aggregate for research and system improvement, not for advertising.
        </li>
      </ul>
      <p style={{ fontSize: 13, color: '#6b7280', maxWidth: 640 }}>
        If you are uncomfortable with this, do not upload sensitive content or personally identifying information.
      </p>
    </main>
  )
}
